### ISSUE TITLE
Token type?

### ISSUE THREAD

**Issue by Classsic** [a-sync/slackfu#1]
Work like a charm!
But i`m new in slack and see the docs about tokens, and this program use legacy token, is rigth?
Wich type have to use in production? (legacy is recomended only for testing).
Thanks.
Classsic.

**Comment by a-sync** [comment]
Related slack docu here: https://api.slack.com/docs/oauth

FYI the [files.upload](https://api.slack.com/methods/files.upload) API method used by the script requires the following token type & scope:
![image](https://user-images.githubusercontent.com/14183614/34645850-5e84d792-f358-11e7-80e0-22966203cdcf.png)

**Comment by a-sync** [comment]
The simplest solution in my opinion is [creating a bot user](https://my.slack.com/services/new/bot) and using it's token:
![image](https://user-images.githubusercontent.com/14183614/34645926-8a6a812a-f35a-11e7-9377-cc4aeefdc02e.png)

**Comment by a-sync** [comment]
Created a wiki page to help with this: https://github.com/a-sync/slackfu/wiki#slack-api-tokens
